/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ResidentsService } from "../residents.service";
import { ResidentsCreateInput } from "./ResidentsCreateInput";
import { Residents } from "./Residents";
import { ResidentsFindManyArgs } from "./ResidentsFindManyArgs";
import { ResidentsWhereUniqueInput } from "./ResidentsWhereUniqueInput";
import { ResidentsUpdateInput } from "./ResidentsUpdateInput";
import { ContractsFindManyArgs } from "../../contracts/base/ContractsFindManyArgs";
import { Contracts } from "../../contracts/base/Contracts";
import { ContractsWhereUniqueInput } from "../../contracts/base/ContractsWhereUniqueInput";

export class ResidentsControllerBase {
  constructor(protected readonly service: ResidentsService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Residents })
  async createResidents(
    @common.Body() data: ResidentsCreateInput
  ): Promise<Residents> {
    return await this.service.createResidents({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phoneNumber: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Residents] })
  @ApiNestedQuery(ResidentsFindManyArgs)
  async residentsItems(@common.Req() request: Request): Promise<Residents[]> {
    const args = plainToClass(ResidentsFindManyArgs, request.query);
    return this.service.residentsItems({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phoneNumber: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Residents })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async residents(
    @common.Param() params: ResidentsWhereUniqueInput
  ): Promise<Residents | null> {
    const result = await this.service.residents({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        email: true,
        phoneNumber: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Residents })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateResidents(
    @common.Param() params: ResidentsWhereUniqueInput,
    @common.Body() data: ResidentsUpdateInput
  ): Promise<Residents | null> {
    try {
      return await this.service.updateResidents({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          phoneNumber: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Residents })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteResidents(
    @common.Param() params: ResidentsWhereUniqueInput
  ): Promise<Residents | null> {
    try {
      return await this.service.deleteResidents({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          email: true,
          phoneNumber: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/contractsItems")
  @ApiNestedQuery(ContractsFindManyArgs)
  async findContractsItems(
    @common.Req() request: Request,
    @common.Param() params: ResidentsWhereUniqueInput
  ): Promise<Contracts[]> {
    const query = plainToClass(ContractsFindManyArgs, request.query);
    const results = await this.service.findContractsItems(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        contractNumber: true,
        startDate: true,
        endDate: true,

        rentHome: {
          select: {
            id: true,
          },
        },

        resident: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/contractsItems")
  async connectContractsItems(
    @common.Param() params: ResidentsWhereUniqueInput,
    @common.Body() body: ContractsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractsItems: {
        connect: body,
      },
    };
    await this.service.updateResidents({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/contractsItems")
  async updateContractsItems(
    @common.Param() params: ResidentsWhereUniqueInput,
    @common.Body() body: ContractsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractsItems: {
        set: body,
      },
    };
    await this.service.updateResidents({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/contractsItems")
  async disconnectContractsItems(
    @common.Param() params: ResidentsWhereUniqueInput,
    @common.Body() body: ContractsWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      contractsItems: {
        disconnect: body,
      },
    };
    await this.service.updateResidents({
      where: params,
      data,
      select: { id: true },
    });
  }
}
