/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CollaboratorsCreateNestedManyWithoutBuildingsItemsInput } from "./CollaboratorsCreateNestedManyWithoutBuildingsItemsInput";
import { Type } from "class-transformer";
import { RentHomesCreateNestedManyWithoutBuildingsItemsInput } from "./RentHomesCreateNestedManyWithoutBuildingsItemsInput";
import { CustomersWhereUniqueInput } from "../../customers/base/CustomersWhereUniqueInput";

@InputType()
class BuildingsCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => CollaboratorsCreateNestedManyWithoutBuildingsItemsInput,
  })
  @ValidateNested()
  @Type(() => CollaboratorsCreateNestedManyWithoutBuildingsItemsInput)
  @IsOptional()
  @Field(() => CollaboratorsCreateNestedManyWithoutBuildingsItemsInput, {
    nullable: true,
  })
  collaboratorsItems?: CollaboratorsCreateNestedManyWithoutBuildingsItemsInput;

  @ApiProperty({
    required: false,
    type: () => RentHomesCreateNestedManyWithoutBuildingsItemsInput,
  })
  @ValidateNested()
  @Type(() => RentHomesCreateNestedManyWithoutBuildingsItemsInput)
  @IsOptional()
  @Field(() => RentHomesCreateNestedManyWithoutBuildingsItemsInput, {
    nullable: true,
  })
  rentHomesItems?: RentHomesCreateNestedManyWithoutBuildingsItemsInput;

  @ApiProperty({
    required: false,
    type: () => CustomersWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CustomersWhereUniqueInput)
  @IsOptional()
  @Field(() => CustomersWhereUniqueInput, {
    nullable: true,
  })
  customer?: CustomersWhereUniqueInput | null;
}

export { BuildingsCreateInput as BuildingsCreateInput };
