/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Buildings } from "./Buildings";
import { BuildingsCountArgs } from "./BuildingsCountArgs";
import { BuildingsFindManyArgs } from "./BuildingsFindManyArgs";
import { BuildingsFindUniqueArgs } from "./BuildingsFindUniqueArgs";
import { CreateBuildingsArgs } from "./CreateBuildingsArgs";
import { UpdateBuildingsArgs } from "./UpdateBuildingsArgs";
import { DeleteBuildingsArgs } from "./DeleteBuildingsArgs";
import { CollaboratorsFindManyArgs } from "../../collaborators/base/CollaboratorsFindManyArgs";
import { Collaborators } from "../../collaborators/base/Collaborators";
import { RentHomesFindManyArgs } from "../../rentHomes/base/RentHomesFindManyArgs";
import { RentHomes } from "../../rentHomes/base/RentHomes";
import { Customers } from "../../customers/base/Customers";
import { BuildingsService } from "../buildings.service";
@graphql.Resolver(() => Buildings)
export class BuildingsResolverBase {
  constructor(protected readonly service: BuildingsService) {}

  async _buildingsItemsMeta(
    @graphql.Args() args: BuildingsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Buildings])
  async buildingsItems(
    @graphql.Args() args: BuildingsFindManyArgs
  ): Promise<Buildings[]> {
    return this.service.buildingsItems(args);
  }

  @graphql.Query(() => Buildings, { nullable: true })
  async buildings(
    @graphql.Args() args: BuildingsFindUniqueArgs
  ): Promise<Buildings | null> {
    const result = await this.service.buildings(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Buildings)
  async createBuildings(
    @graphql.Args() args: CreateBuildingsArgs
  ): Promise<Buildings> {
    return await this.service.createBuildings({
      ...args,
      data: {
        ...args.data,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Buildings)
  async updateBuildings(
    @graphql.Args() args: UpdateBuildingsArgs
  ): Promise<Buildings | null> {
    try {
      return await this.service.updateBuildings({
        ...args,
        data: {
          ...args.data,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Buildings)
  async deleteBuildings(
    @graphql.Args() args: DeleteBuildingsArgs
  ): Promise<Buildings | null> {
    try {
      return await this.service.deleteBuildings(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Collaborators], { name: "collaboratorsItems" })
  async findCollaboratorsItems(
    @graphql.Parent() parent: Buildings,
    @graphql.Args() args: CollaboratorsFindManyArgs
  ): Promise<Collaborators[]> {
    const results = await this.service.findCollaboratorsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [RentHomes], { name: "rentHomesItems" })
  async findRentHomesItems(
    @graphql.Parent() parent: Buildings,
    @graphql.Args() args: RentHomesFindManyArgs
  ): Promise<RentHomes[]> {
    const results = await this.service.findRentHomesItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Customers, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(
    @graphql.Parent() parent: Buildings
  ): Promise<Customers | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
